apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.metadata.name }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: {{ .Values.privateKeySecretRef.name }}
    solvers:
      - http01:
          ingress:
            class: nginx
