containers:
  image: gitlab.praktikum-services.ru:5050/std-028-38/momo-store/momo-store-frontend
  tag: latest
imagePullSecrets: myregistrykey
restartPolicy: Always
imagePullPolicy: IfNotPresent
prometheus_exporter: nginx/nginx-prometheus-exporter:0.10.0
annotations:
  prometheus.io/path: /metrics
  prometheus.io/port: "9113"
  prometheus.io/scrape: "true"
volumeMounts:
  - mountPath: /etc/nginx/conf.d/
    readOnly: true
    name: nginx-conf
volumes:
  - name: nginx-conf
    configMap:
      name: nginx-conf
      items:
        - key: default.conf
          path: default.conf
livenessProbe:
  tcpSocket:
    port: 80
  initialDelaySeconds: 15
  periodSeconds: 20
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

service:
  port: 80

configmap:
  data:
    default.conf: |
      server {
      listen 80;

        location / {
              root /usr/share/nginx/html;
              index index.html index.htm;

              try_files $uri $uri/ /index.html;
        }

        location ~ ^/(?:products|categories|orders|metrics|auth/whoami/catalog) {
              proxy_pass   http://backend:8081;
        }
        location /stub_status {
          allow 127.0.0.1;
          deny all;
          stub_status on;
        }
      }
  name: nginx-conf

hpa:
  maxReplicas: 10
  minReplicas: 1

ingress:
  enabled: true
  host: momo-store.artem4eg.cc
  secretName: momo-store-artem4eg-cc-tls
  ingressClassName: nginx
  port: 80
